set_property PACKAGE_PIN U8 [get_ports GTXQ0_P]
set_property PACKAGE_PIN N8 [get_ports GTXQ0_P2]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_last_fiber_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_last_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_last_fiber_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_last_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_last_fiber_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_last_reg]
set_false_path -from [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst_2/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]


set_property DIFF_TERM TRUE [get_ports FPGA_REFCLK1_P]
set_property DIFF_TERM TRUE [get_ports FPGA_REFCLK1_N]

set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

create_clock -period 8.333 -name GTXQ0_N -waveform {0.000 4.167} -add [get_ports GTXQ0_N]
create_clock -period 8.333 -name GTXQ0_P -waveform {0.000 4.167} -add [get_ports GTXQ0_P]
create_clock -period 8.333 -name GTXQ0_N2 -waveform {0.000 4.167} -add [get_ports GTXQ0_N2]
create_clock -period 8.333 -name GTXQ0_P2 -waveform {0.000 4.167} -add [get_ports GTXQ0_P2]
#set_false_path -from [get_clocks GTXQ0_P] -to [get_clocks GTXQ0_N]


set_property PACKAGE_PIN AA4 [get_ports {RXP[0]}]
#set_property PACKAGE_PIN Y1 [get_ports {TXN[0]}]
#set_property PACKAGE_PIN Y2 [get_ports {TXP[0]}]
set_property PACKAGE_PIN Y6 [get_ports {RXP[1]}]
#set_property PACKAGE_PIN V1 [get_ports {TXN[1]}]
#set_property PACKAGE_PIN V2 [get_ports {TXP[1]}]
set_property PACKAGE_PIN V6 [get_ports {RXP[3]}]
#set_property PACKAGE_PIN T1 [get_ports {TXN[3]}]
#set_property PACKAGE_PIN T2 [get_ports {TXP[3]}]
set_property PACKAGE_PIN W4 [get_ports {RXP[2]}]
#set_property PACKAGE_PIN U3 [get_ports {TXN[2]}]
#set_property PACKAGE_PIN U4 [get_ports {TXP[2]}]

set_property PACKAGE_PIN T6 [get_ports {RXP_2[0]}]
#set_property PACKAGE_PIN P1 [get_ports {TXN_2[0]}]
#set_property PACKAGE_PIN P2 [get_ports {TXP_2[0]}]
set_property PACKAGE_PIN R4 [get_ports {RXP_2[1]}]
#set_property PACKAGE_PIN N3 [get_ports {TXN_2[1]}]
#set_property PACKAGE_PIN N4 [get_ports {TXP_2[1]}]
set_property PACKAGE_PIN P6 [get_ports {RXP_2[2]}]
#set_property PACKAGE_PIN M1 [get_ports {TXN_2[2]}]
#set_property PACKAGE_PIN M2 [get_ports {TXP_2[2]}]
set_property PACKAGE_PIN M6 [get_ports {RXP_2[3]}]
#set_property PACKAGE_PIN L3 [get_ports {TXN_2[3]}]
#set_property PACKAGE_PIN L4 [get_ports {TXP_2[3]}]


set_property PACKAGE_PIN AC22 [get_ports {tx_dis[0]}]
set_property PACKAGE_PIN AA23 [get_ports {tx_dis[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dis[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dis[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports cpib_delay]
set_property PACKAGE_PIN AF20 [get_ports cpib_delay]
set_property IOSTANDARD LVCMOS33 [get_ports cpie_delay]
set_property PACKAGE_PIN AD21 [get_ports cpie_delay]

set_property IOSTANDARD LVCMOS33 [get_ports CPIB]
set_property PACKAGE_PIN AB23 [get_ports CPIB]
set_property IOSTANDARD LVCMOS33 [get_ports CPIE]
set_property PACKAGE_PIN AC24 [get_ports CPIE]
set_property IOSTANDARD LVCMOS33 [get_ports PRI_O]
set_property PACKAGE_PIN AD24 [get_ports PRI_O]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SYNC]
set_property PACKAGE_PIN AD22 [get_ports FPGA_SYNC]

#led
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED0]
set_property PACKAGE_PIN AC25 [get_ports FPGA_LED0]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED1]
set_property PACKAGE_PIN AE25 [get_ports FPGA_LED1]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED2]
set_property PACKAGE_PIN AF25 [get_ports FPGA_LED2]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED3]
set_property PACKAGE_PIN AG25 [get_ports FPGA_LED3]


#FPGA_IO
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[0]}]
set_property PACKAGE_PIN AK26 [get_ports {FPGA_IO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[1]}]
set_property PACKAGE_PIN AF27 [get_ports {FPGA_IO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[2]}]
set_property PACKAGE_PIN AH27 [get_ports {FPGA_IO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[3]}]
set_property PACKAGE_PIN AG28 [get_ports {FPGA_IO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[4]}]
set_property PACKAGE_PIN AK28 [get_ports {FPGA_IO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[5]}]
set_property PACKAGE_PIN AD26 [get_ports {FPGA_IO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[6]}]
set_property PACKAGE_PIN AH30 [get_ports {FPGA_IO[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[7]}]
set_property PACKAGE_PIN AJ29 [get_ports {FPGA_IO[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[8]}]
set_property PACKAGE_PIN AC27 [get_ports {FPGA_IO[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[9]}]
set_property PACKAGE_PIN AD28 [get_ports {FPGA_IO[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[10]}]
set_property PACKAGE_PIN AB30 [get_ports {FPGA_IO[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[11]}]
set_property PACKAGE_PIN AE29 [get_ports {FPGA_IO[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[12]}]
set_property PACKAGE_PIN AA30 [get_ports {FPGA_IO[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[13]}]
set_property PACKAGE_PIN AC30 [get_ports {FPGA_IO[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[14]}]
set_property PACKAGE_PIN AB25 [get_ports {FPGA_IO[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_IO[15]}]
set_property PACKAGE_PIN AB28 [get_ports {FPGA_IO[15]}]

#AD
set_property IOSTANDARD LVCMOS18 [get_ports ADC01_CSB]
set_property IOSTANDARD LVCMOS18 [get_ports ADC01_PDWN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC01_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports ADC01_SDIO]
set_property IOSTANDARD LVCMOS18 [get_ports ADC01_SYNC]
set_property PACKAGE_PIN AF15 [get_ports ADC01_CSB]
set_property PACKAGE_PIN AJ16 [get_ports ADC01_SDIO]
set_property PACKAGE_PIN AH16 [get_ports ADC01_SCLK]
set_property PACKAGE_PIN AK15 [get_ports ADC01_PDWN]
set_property PACKAGE_PIN AG15 [get_ports ADC01_SYNC]
set_property PACKAGE_PIN AC16 [get_ports CH01_AP]
set_property PACKAGE_PIN AB17 [get_ports CH01_BP]
set_property PACKAGE_PIN AC14 [get_ports CH02_AP]
set_property PACKAGE_PIN AE16 [get_ports CH02_BP]
set_property PACKAGE_PIN AH17 [get_ports CH03_AP]
set_property PACKAGE_PIN AJ18 [get_ports CH03_BP]
set_property PACKAGE_PIN AG19 [get_ports CH04_AP]
set_property PACKAGE_PIN AB19 [get_ports CH04_BP]
set_property IOSTANDARD LVDS [get_ports FPGA_REFCLK1_N]
set_property IOSTANDARD LVDS [get_ports FPGA_REFCLK1_P]


set_property PACKAGE_PIN D12 [get_ports CLK_200M_P]
set_property IOSTANDARD LVDS_25 [get_ports CLK_200M_P]
set_property IOSTANDARD LVDS_25 [get_ports CLK_200M_N]

set_property PACKAGE_PIN AD18 [get_ports ADC01_FCO_P]
set_property IOSTANDARD LVDS [get_ports ADC01_FCO_P]
set_property PACKAGE_PIN AD17 [get_ports ADC01_DCO_P]
set_property IOSTANDARD LVDS [get_ports ADC01_DCO_P]
#FPGA_TEST
set_property PACKAGE_PIN AA28 [get_ports {FPGA_TEST[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[0]}]
set_property PACKAGE_PIN W29 [get_ports {FPGA_TEST[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[2]}]
set_property PACKAGE_PIN Y29 [get_ports {FPGA_TEST[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[3]}]
set_property PACKAGE_PIN AA27 [get_ports {FPGA_TEST[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[7]}]
set_property PACKAGE_PIN AE28 [get_ports {FPGA_TEST[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[4]}]
set_property PACKAGE_PIN AF28 [get_ports {FPGA_TEST[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[6]}]
set_property PACKAGE_PIN AE30 [get_ports {FPGA_TEST[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[5]}]
set_property PACKAGE_PIN AF30 [get_ports {FPGA_TEST[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_TEST[1]}]
set_property PACKAGE_PIN AF17 [get_ports FPGA_REFCLK1_P]
set_property PACKAGE_PIN AG17 [get_ports FPGA_REFCLK1_N]

set_property PACKAGE_PIN AA12 [get_ports DAC_RESET_n]
set_property PACKAGE_PIN AB12 [get_ports DAC_CS_n]
set_property PACKAGE_PIN AA8 [get_ports DAC_SPI_SCLK]
set_property PACKAGE_PIN AB8 [get_ports DAC_SPI_SDIO]
set_property PACKAGE_PIN AB9 [get_ports DAC_SPI_SDO]
set_property PACKAGE_PIN AC9 [get_ports DAC_IRQ_n]
set_property PACKAGE_PIN Y11 [get_ports {DAC_DP[0]}]
set_property PACKAGE_PIN AA11 [get_ports {DAC_DP[1]}]
set_property PACKAGE_PIN AD8 [get_ports {DAC_DP[2]}]
set_property PACKAGE_PIN AB10 [get_ports {DAC_DP[3]}]
set_property PACKAGE_PIN AC12 [get_ports {DAC_DP[4]}]
set_property PACKAGE_PIN AD9 [get_ports {DAC_DP[5]}]
set_property PACKAGE_PIN AG9 [get_ports {DAC_DP[6]}]
set_property PACKAGE_PIN AE11 [get_ports {DAC_DP[7]}]
set_property PACKAGE_PIN AJ9 [get_ports {DAC_DP[8]}]
set_property PACKAGE_PIN AH11 [get_ports {DAC_DP[9]}]
set_property PACKAGE_PIN AK11 [get_ports {DAC_DP[10]}]
set_property PACKAGE_PIN AJ13 [get_ports {DAC_DP[11]}]
set_property PACKAGE_PIN AK14 [get_ports {DAC_DP[12]}]
set_property PACKAGE_PIN AE13 [get_ports {DAC_DP[13]}]
set_property PACKAGE_PIN AA13 [get_ports {DAC_DP[14]}]
set_property PACKAGE_PIN AH14 [get_ports {DAC_DP[15]}]
set_property PACKAGE_PIN AF12 [get_ports DAC_DCIP]
set_property IOSTANDARD LVDS [get_ports DAC_DCIP]
set_property PACKAGE_PIN AG13 [get_ports DAC_FRMP]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_FRMP]
set_property PACKAGE_PIN AH12 [get_ports DAC_FRMN]
set_property PACKAGE_PIN AG10 [get_ports DAC_DACLKP]
set_property IOSTANDARD LVDS [get_ports DAC_DACLKP]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CS_n]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_FRMN]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_IRQ_n]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_RESET_n]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SDIO]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SDO]

##################DAC2################
set_property PACKAGE_PIN AD4 [get_ports DAC_RESET_n2]
set_property PACKAGE_PIN AD3 [get_ports DAC_CS_n2]
set_property PACKAGE_PIN AC2 [get_ports DAC_SPI_SCLK2]
set_property PACKAGE_PIN AC1 [get_ports DAC_SPI_SDIO2]
set_property PACKAGE_PIN AD2 [get_ports DAC_SPI_SDO2]
set_property PACKAGE_PIN AD1[get_ports DAC_IRQ_n2]
set_property PACKAGE_PIN AG2 [get_ports DAC_DCIP2]
set_property IOSTANDARD LVDS [get_ports DAC_DCIP2]
set_property PACKAGE_PIN AJ8 [get_ports DAC_FRMP2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_FRMP2]
set_property PACKAGE_PIN AK8 [get_ports DAC_FRMN2]
set_property PACKAGE_PIN AH4 [get_ports DAC_DACLKP2]
set_property IOSTANDARD LVDS [get_ports DAC_DACLKP2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CS_n2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_FRMN2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_IRQ_n2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_RESET_n2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SCLK2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SDIO2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SPI_SDO2]
set_property PACKAGE_PIN AC5 [get_ports {DAC_DP2[0]}]
set_property PACKAGE_PIN AD6 [get_ports {DAC_DP2[1]}]
set_property PACKAGE_PIN AC7 [get_ports {DAC_DP2[2]}]
set_property PACKAGE_PIN AF8 [get_ports {DAC_DP2[3]}]
set_property PACKAGE_PIN AF7 [get_ports {DAC_DP2[4]}]
set_property PACKAGE_PIN AE5 [get_ports {DAC_DP2[5]}]
set_property PACKAGE_PIN AE4 [get_ports {DAC_DP2[6]}]
set_property PACKAGE_PIN AE1 [get_ports {DAC_DP2[7]}]
set_property PACKAGE_PIN AF3 [get_ports {DAC_DP2[8]}]
set_property PACKAGE_PIN AG4 [get_ports {DAC_DP2[9]}]
set_property PACKAGE_PIN AJ3 [get_ports {DAC_DP2[10]}]
set_property PACKAGE_PIN AK5 [get_ports {DAC_DP2[11]}]
set_property PACKAGE_PIN AJ1 [get_ports {DAC_DP2[12]}]
set_property PACKAGE_PIN AH7 [get_ports {DAC_DP2[13]}]
set_property PACKAGE_PIN AH2 [get_ports {DAC_DP2[14]}]
set_property PACKAGE_PIN AJ6 [get_ports {DAC_DP2[15]}]


#set_false_path -from [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins clk_REFclk/inst/mmcm_adv_inst/CLKOUT1]]
#set_false_path -from [get_clocks -of_objects [get_pins clk_REFclk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]]




#set_false_path -from [get_clocks -of_objects [get_pins clk_REFclk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]]
#set_false_path -from [get_clocks -of_objects [get_pins clk_REFclk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]
#set_false_path -from [get_clocks -of_objects [get_pins clk_200m_inst/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]
#set_false_path -from [get_clocks GTXQ0_N] -to [get_clocks GTXQ0_P]





set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[13]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[13]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[15]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[15]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[3]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[3]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[15]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[15]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[5]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[5]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[13]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[13]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[7]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[7]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[11]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[11]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[9]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[9]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[9]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[9]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[7]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[7]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[12]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[12]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[5]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[5]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[0]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[0]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[10]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[10]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[3]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[3]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[1]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[1]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[14]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[14]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[2]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[2]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[4]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[4]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[14]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[14]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[10]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[10]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[6]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[6]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[12]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[12]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[8]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[8]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[8]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[8]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[6]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[6]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[11]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[11]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[4]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[4]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_I_temp_reg[1]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_I/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[1]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[2]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[2]}]
set_property ASYNC_REG true [get_cells {ddc_inst/data_Q_temp_reg[0]}]
set_property ASYNC_REG true [get_cells {ddc_inst/FIR_Q/U0/i_synth/g_single_rate.i_single_rate/g_s_data_chan_fifo.i_s_data_chan_fifo/fifo_wr_data_1_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[53]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[53]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[55]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[55]}]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_valid_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_valid_fiber_reg]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[55]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[55]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[59]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[59]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[3]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[7]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[7]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[59]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[59]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[4]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[19]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[19]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[30]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[42]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[5]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[25]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[13]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[54]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[49]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[37]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[6]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[53]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[53]}]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1_inst/frame_timing_return_para_v1_inst/enable_r_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1_inst/frame_timing_return_para_v1_inst/enable_rr_reg]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[20]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[7]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[7]}]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_valid_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_valid_fiber_reg]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[56]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[32]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[44]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[39]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[27]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[15]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[31]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[14]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[43]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[55]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[55]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[38]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[26]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[61]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[19]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[19]}]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_valid_reg]
set_property ASYNC_REG true [get_cells pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_valid_fiber_reg]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[34]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[46]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[10]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[22]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[29]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[17]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[58]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[1]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[60]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[9]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[45]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[2]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[57]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[21]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[33]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[28]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[16]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[63]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[51]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[41]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[19]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[19]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[8]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[12]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[53]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[53]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[24]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[36]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[48]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[50]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[40]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[62]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[52]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[7]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[7]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[23]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[35]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[11]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/uut/data_frame_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst1/data_frame_fiber_reg[18]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[47]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/uut/data_frame_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst3/data_frame_fiber_reg[0]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/uut/data_frame_reg[59]}]
set_property ASYNC_REG true [get_cells {pre_pro_fiber_top_inst/pre_pro_fiber_top_v1b_inst2/data_frame_fiber_reg[59]}]
create_clock -period 5.000 -name CLK_200M_P -waveform {0.000 2.500} [get_ports CLK_200M_P]
set_clock_groups -asynchronous -group [get_clocks GTXQ0_P] -group [get_clocks GTXQ0_N]
set_clock_groups -asynchronous -group [get_clocks GTXQ0_N] -group [get_clocks GTXQ0_P]
set_clock_groups -asynchronous -group [get_clocks CLK_200M_P] -group [get_clocks user_clk_i]

set_false_path -from [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]


set_false_path -from [get_clocks CLK_200M_P] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst_2/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]

set_false_path -from [get_clocks CLK_200M_P] -to [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks GTXQ0_N2] -to [get_clocks GTXQ0_P2]
set_false_path -from [get_clocks GTXQ0_P2] -to [get_clocks GTXQ0_N2]
set_false_path -from [get_clocks -of_objects [get_pins clk_200m_inst/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins clk_200m_inst/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst_2/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]]

set_false_path -from [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins pre_pro_fiber_top_inst_2/aurora_64b66b_4_exdes_inst/aurora_64b66b_4_block_i/clock_module_i/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins ad_inst/clk_fpga_inst/inst/plle2_adv_inst/CLKOUT0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_ad_120m]


set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets ad_inst/clk_fpga_inst/inst/clk_in1_clk_ad_0]